### ISSUE TITLE
Progress bar not showing when running tasks

### ISSUE THREAD

**Issue by GustavLundberg** [SHAARPEC/shaarpec-python-client#1]
When trying to run tasks with client.run() the progress bar would not show up, even though the task finished successfully and progress was correctly reported during the execution of the task.

To get it to work I had to:

`pip install ipywidgets`

When restarting my jupyter lab session, I got the following:
[AttributeError: module 'collections' has no attribute 'MutableMapping'](https://stackoverflow.com/questions/70943244/attributeerror-module-collections-has-no-attribute-mutablemapping)

which was solved with:
`pip install --upgrade requests`

**Comment by erikgbrandt** [comment]
This should be solved in v.2.2.0. A bug in tqdm and jupyter notebook. The library use the ASCII version of the tqdm progress bar for now.
