### ISSUE TITLE
Flexible handling of the timeout limit

### ISSUE THREAD

**Issue by mo-skoltech** [SHAARPEC/shaarpec-python-client#5]
Currently there is a [overwrite on the timeout](https://github.com/SHAARPEC/shaarpec-python-client/blob/496e52acb89832e89d2d796ce5972724b949a53a/shaarpec/client.py#LL71C9-L71C44) parameter on the GET methods of the client. Although this being a good practice, it can cause issues when the user is trying to perform more time consuming GETs.
A simple example that I have faced is:

`population = client.get("population")`

which can be fixed by relaxing the aforementioned hard overwrite and allowing it be altered at the class instantiation.

**Comment by erikgbrandt** [comment]
Thanks for reporting this. Your fix overwrites the timeout on the `httpx.Client` but does not allow individual `get`/`post`/`run` operations to have individual timeouts. A more flexible way is to just forward such parameters. This is implemented in #8 and will be in the 2.5.0 release.

This will allow you to:
```python
from shaarpec import Client
client = Client.with_device("https://api.myshaarpecinstance.com", auth=".auth.my.credentials") # default timeout on calls is 60 s.
response = client.post("population", httpx_kwargs={"timeout": 120}) # call with 120 seconds timeout.
```
